name: 'Check if version bumped'
description: 'Checks if version is bumped in package.json in pull requests'
inputs:
  token:
    description: 'Token to use to retrieve base file. Needed only on private repositories'
    required: false
    default: ''
  node-path:
    description: 'Directory of package.json file (Ex: my-node-dir/)'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: info
  color: yellow
